{{- if .Values.podDisruptionBudget.enabled }}
{{- $api := index .Values.components "api" }}
{{- if $api.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ printf "%s-api" (include "tax-stamps.fullname" .) | trunc 63 | trimSuffix "-" }}
  labels:
    {{- include "tax-stamps.labels" . | nindent 4 }}
    app.kubernetes.io/component: api
spec:
  minAvailable: {{ .Values.podDisruptionBudget.minAvailable }}
  selector:
    matchLabels:
      {{- include "tax-stamps.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: api
{{- end }}
{{- end }}
