apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespaces/platform.yaml
  - namespaces/security.yaml
  - namespaces/recovery.yaml
  - namespaces/ports.yaml
  - namespaces/ferries.yaml
  - namespaces/cvff.yaml
  - namespaces/seafarer.yaml
  - namespaces/fisheries.yaml
  - namespaces/isr.yaml
