{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ default (printf "%s-sedona" .Release.Name) .Values.serviceAccount.name | trunc 63 | trimSuffix "-" }}
  labels:
    app.kubernetes.io/name: sedona-spark-jobs
    app.kubernetes.io/instance: {{ .Release.Name }}
    blueeconomy.platform/criticality: governed-geospatial-analytics
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: {{ .Values.serviceAccount.automountServiceAccountToken }}
{{- end }}
