{{- if and .Values.podDisruptionBudget.enabled (gt (int .Values.replicas) 1) }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "beneficiary-portal.fullname" . }}
  labels:
    {{- include "beneficiary-portal.labels" . | nindent 4 }}
spec:
  maxUnavailable: {{ .Values.podDisruptionBudget.maxUnavailable }}
  selector:
    matchLabels:
      {{- include "beneficiary-portal.selectorLabels" . | nindent 6 }}
{{- end }}
